language: python

# The following two settings are required to get python 3.7
# support on travis for now
# See https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
sudo: required
dist: xenial

python:
  - "3.5"
  - "3.6"
  - "3.7"


install:
  # To work around a problem with wilson package we take the git master version of it
  # - "pip3 install git+https://github.com/wilson-eft/wilson.git"
  - "pip3 install .[plotting,dev]"
  # - "python3 examples/jupyter_notebooks/test/generate_tests.py"
  - "pip3 install coveralls"

script:
  - "pytest --cov=clusterking"

after_success: coveralls
