language: python

python:
  - "3.5"

install:
  # To work around a problem with wilson package we take the git master version of it
  - "pip3 install git+https://github.com/wilson-eft/wilson.git"
  - "pip3 install ."
  - "pip3 install nose2"
  # - "python3 examples/jupyter_notebooks/test/generate_tests.py"
  - "pip3 install coveralls"

script: 
  - "nose2 --with-coverage"

after_success: coveralls

